# Define the GitLab CI/CD pipeline stages
stages:
  - test
  - build

# Define job for testing
test:
  stage: test
  script:
    - pip install -r requirements.txt  # Install project dependencies
    - pytest                           # Run your tests using pytest

# Define job for building Docker image and saving it locally
build:
  stage: build
  script:
    - docker build -t my-python-app .  # Build the Docker image from the Dockerfile
    - docker save -o my-python-app.tar my-python-app  # Save the Docker image to a .tar file
  artifacts:
    paths:
      - my-python-app.tar  # Archive the .tar file as a build artifact
  only:
    - main  # Only run this job on the 'master' branch
