import uuid

from app.core.lab.items_details import ItemConnection, ItemState, ItemQuality
from app.core.lab.laboratory import LabDataItem


class Card(LabDataItem):
    component_id: uuid.UUID = ...
    index: int = ...
    card_type: ItemQuality = ...


class Port(LabDataItem):
    component_id: uuid.UUID = ...
    state: ItemConnection = ...
    index: int = ...
    card_index: int = ...


class Component(LabDataItem):
    comp_id: uuid.UUID = ...
    version: int = ...
    state: ItemState = ...
    card_index: int = ...
